---
- name: Setup New Mac Environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    dotfiles_dir: "{{ lookup('env','HOME') }}/dotfiles"

  tasks:
    - name: Install Xcode Command Line Tools
      command: xcode-select --install
      ignore_errors: yes

    - name: Install Homebrew
      shell: |
        which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install Homebrew packages from Brewfile
      shell: brew bundle --file={{ dotfiles_dir }}/Brewfile
      environment:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Copy Zsh config
      copy:
        src: "{{ dotfiles_dir }}/zshrc"
        dest: "~/.zshrc"
        backup: yes

    - name: Copy Oh My Zsh
      copy:
        src: "{{ dotfiles_dir }}/oh-my-zsh"
        dest: "~/.oh-my-zsh"
        remote_src: yes

    - name: Copy Starship config
      copy:
        src: "{{ dotfiles_dir }}/starship.toml"
        dest: "~/.config/starship.toml"
        backup: yes

    - name: Create Raycast config directory
      file:
        path: "~/Library/Application Support/com.raycast.macos"
        state: directory

    - name: Restore Raycast configuration
      shell: |
        if [ -d "{{ dotfiles_dir }}/raycast" ]; then
          rsync -av --exclude='cache/' --exclude='logs/' --exclude='tmp/' --exclude='*.log' \
                --exclude='node_modules/' --exclude='extensions/*/node_modules/' \
                --exclude='extensions/*/.git/' --exclude='extensions/*/dist/' \
                --exclude='extensions/*/.cache/' --exclude='quicklink-cache.json' \
                --exclude='raycast.db-*' --exclude='*.sqlite-*' \
                "{{ dotfiles_dir }}/raycast/" \
                "~/Library/Application Support/com.raycast.macos/"
        fi
      ignore_errors: yes

    - name: Import keyboard shortcuts
      shell: |
        defaults import com.apple.symbolichotkeys {{ dotfiles_dir }}/symbolichotkeys.plist

    - name: Create Downloads directory for manual apps
      file:
        path: "~/Downloads/manual_apps"
        state: directory

    - name: Download Microsoft Office
      get_url:
        url: "https://go.microsoft.com/fwlink/?linkid=525133"
        dest: "~/Downloads/manual_apps/Microsoft_Office_installer.pkg"
        mode: '0644'

    - name: Download Zoom
      get_url:
        url: "https://zoom.us/client/latest/ZoomInstaller.pkg"
        dest: "~/Downloads/manual_apps/ZoomInstaller.pkg"
        mode: '0644'

    - name: Download uTorrent Web
      get_url:
        url: "https://download-new.utorrent.com/endpoint/utorrent/os/mac"
        dest: "~/Downloads/manual_apps/uTorrent_Web.dmg"
        mode: '0644'

    - name: Download Zen Browser
      get_url:
        url: "https://github.com/zen-browser/desktop/releases/latest/download/zen.macos-universal.dmg"
        dest: "~/Downloads/manual_apps/zen.macos-universal.dmg"
        mode: '0644'

    - name: Download Pinokio
      get_url:
        url: "https://github.com/pinokiocomputer/pinokio/releases/latest/download/Pinokio-darwin-arm64.zip"
        dest: "~/Downloads/manual_apps/Pinokio-darwin-arm64.zip"
        mode: '0644'

    - name: Download folk
      get_url:
        url: "https://folk.computer/download/mac"
        dest: "~/Downloads/manual_apps/folk.dmg"
        mode: '0644'

    - name: Display manual installation message
      debug:
        msg: |
          Downloaded apps are in ~/Downloads/manual_apps/
          Please manually install:
          - Microsoft Office (.pkg)
          - Zoom (.pkg) 
          - uTorrent Web (.dmg)
          - Zen Browser (.dmg)
          - Pinokio (.zip)
          - folk (.dmg)
          
          See manual_install.txt for other apps that need manual installation.